name: Website Health Check

on:
  push:

jobs:
  check-website:
    runs-on: ubuntu-latest

    steps:
      - name: Check Website
        run: |
          if curl --fail https://www.google.com; then
            echo "Website is working!"
          else
            echo "Website is DOWN!"
            exit 1
          fi
