name: Website Health Check

on:
  push:

jobs:
  check-website:
    runs-on: ubuntu-latest

    steps:
      - name: Check Website
        run: curl --fail https://example.com

      - name: Success Message
        run: echo "Website is working!"
